import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import NavBar from '../components/Navigation/NavBar';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Invoice App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main></main>
    </div>
  );
};

export default Home;
